name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-dev
          pip3 install --user --upgrade buildozer cython==0.29.33 virtualenv

      - name: Build with Buildozer
        run: |
          # SDK ve NDK yollarını netleştiriyoruz
          export PATH=$PATH:$HOME/.local/bin
          # Hata ayıklama modunda çalıştır (Loglar daha net gelir)
          buildozer android debug || { echo "HATA OLUSTU, LOGLARI KONTROL ET"; exit 1; }
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
          BUILDZEL_WARN_ON_ROOT: "0"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Vervain-APK
          path: bin/*.apk
          
