name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Önbellek (Cache) ekleyerek süreyi 15 dakikadan 3-4 dakikaya indiririz
      - name: Cache Buildozer
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-dev
          pip3 install --user --upgrade buildozer cython==0.29.33 virtualenv

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Logların şişmemesi için sadece kritik hataları görelim (log_level = 1)
          # 'warn' seviyesinde çalıştırarak 'truncated' hatasını önlemeye çalışıyoruz
          buildozer -v android debug || buildozer android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
          BUILDZEL_WARN_ON_ROOT: "0"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Vervain-APK
          path: bin/*.apk
          
