      - name: Build with Buildozer
        run: |
          export PATH=$PATH:$HOME/.local/bin
          # Önce tüm Android lisanslarını otomatik olarak 'yes' diyerek onayla
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | /home/runner/.buildozer/android/platform/android-sdk/tools/bin/sdkmanager --sdk_root=/home/runner/.buildozer/android/platform/android-sdk --licenses || true
          
          # Şimdi derlemeyi başlat
          buildozer android debug
        env:
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
          BUILDZEL_WARN_ON_ROOT: "0"
          
