name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip build-essential git zip unzip openjdk-17-jdk autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev
          pip3 install buildozer==1.5.0 cython==0.29.33 setuptools

      - name: Build APK
        run: |
          # Önce lisansları kabul etmeyi zorla
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          # Buildozer'ın kendi içindeki 'yes' mekanizmasını kullan
          buildozer android debug || buildozer android debug
        env:
          # Lisansları otomatik onaylaması için Buildozer'a talimat
          APP_ANDROID_ACCEPT_SDK_LICENSE: "1"
          BUILDZEL_WARN_ON_ROOT: "0"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Vervain-APK
          path: bin/*.apk
          
